name: Deploy Direct

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore and Build
      run: |
        cd backend/AttendanceSystem.API
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet publish --configuration Release --no-build --output ./publish

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'asistenciaestudiantil'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
        package: './backend/AttendanceSystem.API/publish'

    - name: Verify deployment
      run: |
        echo "Deployment completed!"
        echo "API URL: http://asistenciaestudiantil-gefwbed2f7h8csd8.canadacentral-01.azurewebsites.net"
        echo "Swagger: http://asistenciaestudiantil-gefwbed2f7h8csd8.canadacentral-01.azurewebsites.net/swagger"
