name: Deploy Simple

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend to Existing App Service
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: |
        cd backend/AttendanceSystem.API
        dotnet restore

    - name: Build application
      run: |
        cd backend/AttendanceSystem.API
        dotnet build --configuration Release --no-restore

    - name: Publish application
      run: |
        cd backend/AttendanceSystem.API
        dotnet publish --configuration Release --no-build --output ./publish

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'GPSAlumniBT'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
        package: './backend/AttendanceSystem.API/publish'

    - name: Test deployment
      run: |
        sleep 30
        echo "Testing deployment..."
        curl -f https://gpsalumnibt-cyadgxdbegbgb8f6.canadacentral-01.azurewebsites.net || echo "App is starting up..."
