name: Test Secrets Configuration

on:
  workflow_dispatch:

jobs:
  test-secrets:
    name: Test GitHub Secrets
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Test Azure Secrets
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        echo "🔍 Verificando secrets de Azure..."
        
        if [ -z "$AZURE_CLIENT_ID" ]; then
          echo "❌ ERROR: AZURE_CLIENT_ID no está configurado"
          exit 1
        else
          echo "✅ AZURE_CLIENT_ID: Configurado (${#AZURE_CLIENT_ID} caracteres)"
        fi
        
        if [ -z "$AZURE_CLIENT_SECRET" ]; then
          echo "❌ ERROR: AZURE_CLIENT_SECRET no está configurado"
          exit 1
        else
          echo "✅ AZURE_CLIENT_SECRET: Configurado (${#AZURE_CLIENT_SECRET} caracteres)"
        fi
        
        if [ -z "$AZURE_SUBSCRIPTION_ID" ]; then
          echo "❌ ERROR: AZURE_SUBSCRIPTION_ID no está configurado"
          exit 1
        else
          echo "✅ AZURE_SUBSCRIPTION_ID: Configurado (${#AZURE_SUBSCRIPTION_ID} caracteres)"
        fi
        
        if [ -z "$AZURE_TENANT_ID" ]; then
          echo "❌ ERROR: AZURE_TENANT_ID no está configurado"
          exit 1
        else
          echo "✅ AZURE_TENANT_ID: Configurado (${#AZURE_TENANT_ID} caracteres)"
        fi

    - name: Test Deployment Secrets
      env:
        AZURE_WEBAPP_PUBLISH_PROFILE_API: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
        AZURE_SQL_CONNECTION_STRING: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
      run: |
        echo "🔍 Verificando secrets de deployment..."
        
        if [ -z "$AZURE_WEBAPP_PUBLISH_PROFILE_API" ]; then
          echo "❌ ERROR: AZURE_WEBAPP_PUBLISH_PROFILE_API no está configurado"
        else
          echo "✅ AZURE_WEBAPP_PUBLISH_PROFILE_API: Configurado (${#AZURE_WEBAPP_PUBLISH_PROFILE_API} caracteres)"
        fi
        
        if [ -z "$AZURE_SQL_CONNECTION_STRING" ]; then
          echo "⚠️  ADVERTENCIA: AZURE_SQL_CONNECTION_STRING no está configurado (opcional)"
        else
          echo "✅ AZURE_SQL_CONNECTION_STRING: Configurado (${#AZURE_SQL_CONNECTION_STRING} caracteres)"
        fi

    - name: Test Azure CLI Login
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        echo "🔍 Probando login a Azure..."
        
        # Install Azure CLI
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        
        # Login with service principal
        az login --service-principal \
          --username $AZURE_CLIENT_ID \
          --password $AZURE_CLIENT_SECRET \
          --tenant $AZURE_TENANT_ID
        
        # Set subscription
        az account set --subscription $AZURE_SUBSCRIPTION_ID
        
        # Verify login
        echo "✅ Login exitoso a Azure"
        az account show --output table

    - name: Test App Service Access
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        echo "🔍 Verificando acceso al App Service..."
        
        # Check if App Service exists
        APP_EXISTS=$(az webapp list --query "[?name=='asistenciaestudiantil'].name" --output tsv)
        
        if [ -n "$APP_EXISTS" ]; then
          echo "✅ App Service 'asistenciaestudiantil' encontrado"
          
          # Get App Service details
          az webapp show --name asistenciaestudiantil --resource-group pds --output table
          
          # Check App Service status
          STATUS=$(az webapp show --name asistenciaestudiantil --resource-group pds --query "state" --output tsv)
          echo "📊 Estado del App Service: $STATUS"
          
        else
          echo "❌ ERROR: App Service 'asistenciaestudiantil' no encontrado"
          echo "📋 App Services disponibles:"
          az webapp list --output table
        fi

    - name: Test Publish Profile
      env:
        AZURE_WEBAPP_PUBLISH_PROFILE_API: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
      run: |
        echo "🔍 Verificando formato del Publish Profile..."
        
        if [[ "$AZURE_WEBAPP_PUBLISH_PROFILE_API" == *"<publishData>"* ]]; then
          echo "✅ Publish Profile tiene formato XML correcto"
        else
          echo "❌ ERROR: Publish Profile no tiene formato XML válido"
        fi
        
        if [[ "$AZURE_WEBAPP_PUBLISH_PROFILE_API" == *"asistenciaestudiantil"* ]]; then
          echo "✅ Publish Profile contiene el nombre correcto del App Service"
        else
          echo "❌ ERROR: Publish Profile no contiene 'asistenciaestudiantil'"
        fi

    - name: Summary
      run: |
        echo ""
        echo "🎯 RESUMEN DE VERIFICACIÓN:"
        echo "✅ Secrets de Azure configurados"
        echo "✅ Login a Azure exitoso"
        echo "✅ App Service accesible"
        echo "✅ Publish Profile válido"
        echo ""
        echo "🚀 ¡Tus secrets están configurados correctamente!"
        echo "💡 Puedes proceder con el deployment usando 'Deploy Simple'"
